kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-delete
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "replicationcontrollers", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]
  - apiGroups: ["apps"]
    resources: ["statefulsets", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets", "job"]
    verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: auto-delete
subjects:
- kind: ServiceAccount
  name: auto-delete
roleRef:
  kind: Role
  name: auto-delete
  apiGroup: ""

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auto-delete
---
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: auto-delete
spec:
  jobTemplate:
    metadata:
      name: auto-delete
    spec:
      completions: 1
      template:
        spec:
          containers:
            -
              command: ["/bin/sh","-c"]
              args: ["kubectl delete deploy nodeapp; kubectl delete hpa hpa-nodeapp"]
              image: "bitnami/kubectl:latest"
              name: auto-delete
          restartPolicy: OnFailure
  schedule: "*/5 * * * *"
