---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongodb-svc
  name: mongodb-svc
spec:
  ports:
    -
      name: http
      port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongodb
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeName: ip-172-31-16-180
      containers:
        -
          image: "mongo:latest"
          name: mongodb
          ports:
            -
              containerPort: 27017
              name: mongodb
          volumeMounts:
          - mountPath: /data/db
            name: test-volume
      volumes:
      - name: test-volume
        hostPath:
          path: /home/ubuntu/mongodb_data
          type: DirectoryOrCreate
